name: CI

on:
   push:
    branches: [ "master" ]

jobs:
  # This workflow contains a single job called "build"
  lab_check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          python -m pip install pytest
          python -m pip install pytest-golden
          python -m pip install ruff

      - name: run pytest
        run: |
          export PYTHONPATH=/home/runner/work/CSA-lab3/CSA-lab3/.
          cd src
          python -m pytest golden_test.py

      - name: ruff
        run: |
          python -m ruff check ./src/translator.py
          python -m ruff check ./src/machine.py
          python -m ruff check ./src/machine.py

