name: CI

on:
   push:
    branches: [ "master" ]

jobs:
  # This workflow contains a single job called "build"
  lab_check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          python -m pip install pytest

      - name: run pytest
        run: |
          export PYTHONPATH=/home/runner/work/CSA-lab3/CSA-lab3/.
          python -m pytest src/golden_test.py
